blank_issues_enabled: true
contact_links:
  - name: Account Limit Increase Request
    url: https://mailxto.com/xy5ijb
    about: Submit a request to increase the size limit on your Web3.Storage account!
  - name: Pinning Service Access Request
    url: https://mailxto.com/h58kmo
    about: Submit a request to access Web3.Storage's IPFS pinning service in your account!