# filecoin.storage wrangler config.

name = "filecoin-storage"
# `javascript` means our we'll send pre-built javascript code. 
#  ...as opposed to `webpack` where wrangler builds our code for us.
type = "javascript"

# tell wrangler how to build our service-worker bundle
[build]
command = "npm run build"
watch_dir = "src"
[build.upload]
format = "service-worker"

# ---- Environment specific overrides below ! ----

# PROD!
[env.production]
# name = "filecoin-storage-production"
account_id = "?"

# Add your env here. Override the the values you need to change.

[env.alanshaw]
workers_dev = true
account_id = "4fe12d085474d33bdcfd8e9bed4d8f95"

[env.oli]
# NOTE: wrangler automatically assings each env the root `name` with the env name suffixed on the end
# name = "filecoin-storage-oli"
# NOTE: wrangler tries to find an account_id defined at the root if workers_dev = true is not provided on your env.
workers_dev = true
account_id = "6e5a2aed80cd37d77e8d0c797a75ebbd"

# Create your env name as the value of `whoami` on your system, so you can run `npm start` to run in dev mode.
# Copy this template and fill out the values
# [env.${whoami}]
# workers_dev = true
# account_id = "<get me from `wrangler whoami`"
