name: Cron Backup Pins

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      limit:
        description: 'The limit of records to backup'
        default: 10000
      debug:
        description: 'How verbose you want the logs to be. Use backupPins:debug for extra info'
        default: 'backupPins:log'

jobs:
  update:
    name: Backup Pins
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ['staging', 'production']
    concurrency: psa-pin-backup
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout latest cron release tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 --match='cron-*')
          git checkout $LATEST_TAG
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - name: Run job
        env:
          DEBUG: ${{ github.event.inputs.debug || 'backupPins:log' }}
          ENV: ${{ matrix.env }}
          STAGING_PG_CONNECTION: ${{ secrets.STAGING_PG_CONNECTION }}
          STAGING_RO_PG_CONNECTION: ${{ secrets.STAGING_PG_CONNECTION }} # no replica for staging
          PROD_PG_CONNECTION: ${{ secrets.PROD_PG_CONNECTION }}
          PROD_RO_PG_CONNECTION: ${{ secrets.PROD_RO_PG_CONNECTION }}
          QUERY_LIMIT: ${{ github.event.inputs.limit }}
        run: npm run start:pins:backup -w packages/cron

      - name: Heartbeat
        if: ${{ success() }}
        run: ./packages/tools/scripts/cli.js heartbeat --token ${{ secrets.OPSGENIE_KEY }} --name cron-web3storage-backup-pins
